version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql:/sql
  hommabot2:
    build: .
    image: eu.gcr.io/jan-systems/hommabot2:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000

volumes:
  dbdata:
