version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./sql:/sql
  hommabot2:
    build: .
    image: registry.jan.systems/hommabot2:latest
    env_file: .env
    environment:
      PORT: 3000
      PG_CONNECTION_URI: postgresql://postgres:postgres@db/postgres
    ports:
      - 3000:3000

volumes:
  dbdata:
